[project]
name = "specrel"
version = "0.1.0"
authors = [
    { name="Johann Gan" }
]
description = "Special relativity visualization sandbox"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/johanngan/special_relativity"
Issues = "https://github.com/johanngan/special_relativity/issues"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

